name: better_social_share_example
description: Demonstrates and manually QA-tests the better_social_share plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  better_social_share:
    path: ../
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
